apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-guard.fullname" . }}-policy
  labels:
    {{- include "query-guard.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{ .Values.policy | indent 4 }}