apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "query-guard.fullname" . }}
  labels:
    {{- include "query-guard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "query-guard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "query-guard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-config"
            - "/etc/query-guard/policy.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.probes.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: {{ .Values.probes.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: policy
              mountPath: /etc/query-guard
              readOnly: true
      volumes:
        - name: policy
          configMap:
            name: {{ include "query-guard.fullname" . }}-policy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}