apiVersion: v1
kind: Service
metadata:
  name: {{ include "query-guard.fullname" . }}
  labels:
    {{- include "query-guard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.tls.enabled }}https{{ else }}http{{ end }}
      protocol: TCP
      name: {{ if .Values.tls.enabled }}https{{ else }}http{{ end }}
  selector:
    {{- include "query-guard.selectorLabels" . | nindent 4 }}